udp example
mkrufky/dvbtee-express pull request #1
Opened 2017-07-08 09:38 UTC by Pymossy

create a basic example to use node-dvbtee with udp socket

2017-07-11 10:02 UTC, mkrufky requested changes
Thanks for your contribution!  The only issues I have are with the `README.md` - remember that this repo is a basic example for various simple interfaces, not only udp.  If you want to have a `README.md` that's dedicated to udp, then it shouldn't be in the top level of the repository.  I'll be happy to merge once we can address that issue.

2017-07-11 10:02 UTC, mkrufky commented on README.md
> +This is a basic example of how to use node-dvbtee with udp socket.
I'd be happy to merge your code, but remember that the `README.md` is for the entire repository.  Can you change "with udp socket" to something more like "using various interfaces / methods" or something else that you think may be more appropriate.

2017-07-11 10:02 UTC, mkrufky commented on README.md
> +Thanks a lot to @mirmilad
not going to thank me ?  O:-)  I think we can omit this line from the `README.md` ... If you want to instead create a `CONTRIBUTORS` file, include mirmilad, yourself and I.

2017-07-11 10:02 UTC, mkrufky commented on README.md
> +Extract EPG information and other metadata from mpegts udp stream.
Please either make this general or include usage info for all of the interfaces currently supported.

2017-09-07 10:02 UTC, Pymossy commented
Thank you, I solved all issues

2017-09-20 11:15 UTC, mkrufky commented
@Pymossy , pardon the late reply.  It's been a busy summer, and github notifications don't seem to be working for me :-/  I only noticed your comment yesterday.

I want to rewrite the README.md, so I'm going to rename yours to README-UDP for now, but I've merged your actual code changes in bcba8234027db19557917ae64a8b25f594a01fc9 to my master branch.

Again, thank you for your contribution.

2017-09-20 11:15 UTC, closed without merging